package io.github.krzkawa.bambuddyaio.nfc

/**
 * A captured Mifare Classic 1K dump, loaded from `src/test/resources/tagdumps`.
 *
 * Dump files are one block per line as `NN: <32 hex chars>`, the shape the usual Mifare
 * dump tools print. Lines starting with `#` are comments. They are regenerated by
 * `app/tools/generate_tag_dumps.py`, which builds them to the published block layout and
 * signs each sector trailer with the key the published derivation produces for that
 * dump's UID.
 */
class TagDump(val name: String, val blocks: List<ByteArray>) {

    val uid: ByteArray get() = blocks[0].copyOfRange(0, UID_LENGTH)

    val uidHex: String get() = BambuBlocks.hex(uid)

    /** Key A of [sector], as stored in that sector's trailer block. */
    fun keyA(sector: Int): ByteArray =
        blocks[sector * BambuSectors.BLOCKS_PER_SECTOR + 3].copyOfRange(0, BambuKeys.KEY_LENGTH)

    /** The data blocks of sectors 0-4, as [BambuBlocks.parse] wants them. */
    fun dataBlocks(): MutableMap<Int, ByteArray> {
        val out = LinkedHashMap<Int, ByteArray>()
        for (index in BambuSectors.DATA_BLOCKS) out[index] = blocks[index].copyOf()
        return out
    }

    /**
     * A [MifareSectorSource] backed by this dump, which hands out a block only when its
     * sector was authenticated with the right Key A. That way a read test exercises the
     * real authentication path and not just the parsing.
     */
    fun asSource(uidOverride: ByteArray? = null): RecordingSource = RecordingSource(uidOverride ?: uid)

    inner class RecordingSource(override val uid: ByteArray) : MifareSectorSource {
        private val authenticated = mutableSetOf<Int>()

        override val sectorCount: Int = BambuKeys.SECTORS

        /** Sectors the reader asked for, in order, so a test can assert it reads no more than it needs. */
        val attemptedSectors = mutableListOf<Int>()

        /** Blocks the reader actually read. */
        val readBlocks = mutableListOf<Int>()

        /** When set, reading this block throws as if the tag had left the field. */
        var loseTagAtBlock: Int? = null

        /** Sectors to refuse whatever key is presented, standing in for a tag that lacks them. */
        val lockedSectors = mutableSetOf<Int>()

        override fun authenticateSectorWithKeyA(sector: Int, key: ByteArray): Boolean {
            attemptedSectors += sector
            if (sector in lockedSectors) return false
            val accepted = key.contentEquals(keyA(sector))
            if (accepted) authenticated += sector
            return accepted
        }

        override fun readBlock(block: Int): ByteArray {
            val sector = block / BambuSectors.BLOCKS_PER_SECTOR
            check(sector in authenticated) { "block $block read without authenticating sector $sector" }
            if (block == loseTagAtBlock) throw TagLostException("tag left the field at block $block")
            readBlocks += block
            return blocks[block].copyOf()
        }
    }

    companion object {
        private const val UID_LENGTH = 4
        private const val BLOCK_COUNT = 64
        private const val BLOCK_SIZE = 16

        fun load(name: String): TagDump {
            val text = TagDump::class.java.getResourceAsStream("/tagdumps/$name")
                ?.bufferedReader()
                ?.readText()
                ?: error("no tag dump named $name on the test classpath")

            val blocks = text.lineSequence()
                .map { it.trim() }
                .filter { it.isNotEmpty() && !it.startsWith("#") }
                .map { line ->
                    val hex = line.substringAfter(':').trim()
                    require(hex.length == BLOCK_SIZE * 2) { "bad block line in $name: $line" }
                    ByteArray(BLOCK_SIZE) { i -> hex.substring(i * 2, i * 2 + 2).toInt(16).toByte() }
                }
                .toList()

            require(blocks.size == BLOCK_COUNT) { "$name has ${blocks.size} blocks, expected $BLOCK_COUNT" }
            return TagDump(name, blocks)
        }

        /** Reads the whole dump and parses it, the way a successful phone scan would. */
        fun scan(name: String): SpoolTag {
            val dump = load(name)
            return BambuBlocks.parse(dump.uidHex, BambuSectors.read(dump.asSource()))
        }
    }
}
